
project_id = "yxdxwfzkqyovznqjffcm"

[functions.stripe-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.boost-profile]
verify_jwt = true
