
project_id = "yxdxwfzkqyovznqjffcm"

[functions.paystack-checkout]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.boost-profile]
verify_jwt = true
